version: '2'

services:
  info_api:
    container_name: info_api
    build: ./information_api
    restart: always
    volumes:
      - ./information_api:/app
    ports:
      - "8003:8003"
  info_dashboard:
    container_name: info_dashboard
    build: ./dashboard
    restart: always
    volumes:
      - ./dashboard:/app
      - /app/node_modules
    ports:
      - "80:3000"
    env_file: ./dashboard/.env
